=== henrynguyen1/WSD-2018/web/WEB-INF/Textbook.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://au.edu.uts.wsd/project"
           xmlns="https://au.edu.uts.wsd/project"
           elementFormDefault="qualified">
    
    <xs:simpleType name="date">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>   


    <xs:element name="textbooks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="textbook" maxOccurs="unbound">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="ISBN" type="xs:string"/>
                            <xs:element name="date" type="date"/>
                            <xs:element name="abstracts" type="xs:string"/>
                            <xs:element name="category" type="xs:string"/>
                            <xs:element name="reservation" type="xs:string"/>
                            <xs:element name="condition" type="xs:string"/>
                            <xs:element name="lister" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="bookID" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== henrynguyen1/WSD-2018/web/WEB-INF/Textbook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<?xml-stylesheet type="text/xsl" href="Textbook.xsl"?> -->
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<textbooks
    xmlns="https://au.edu.uts.wsd/project" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="https://au.edu.uts.wsd/project Textbook.xsd">>
    <textbook bookID="1">
        <title>Violent Python</title>
        <author>TJ Oconnor</author>
        <ISBN> 1597499579</ISBN>
        <publisher>Syngress</publisher>
        <date>9/22/2012</date>
        <abstracts>Violent Python shows you how to move from a theoretical understanding of offensive computing concepts to a practical implementation. </abstracts>
        <category>IT</category>
        <reservation>No</reservation>
        <condition>new</condition>
        <lister>Michael Nguyen</lister>

    </textbook>
    <textbook bookID="2">

        <title>Black hat Python: Python Programming for hackers and pentesters</title>
        <author>Justin Seitz</author>

        <ISBN>1593275900</ISBN>
        <publisher>No Starch Press</publisher>
        <date>21/12/2014</date>
        <abstracts>
            In Black Hat Python, the latest from Justin Seitz (author of the best-selling Gray Hat Python),youâ€™ll explore the  darker side of Python.
        </abstracts>
        <category>IT</category>
        <reservation>yes</reservation>
        <condition>fair</condition>
        <lister>Michael Nguyen</lister>

    </textbook>
    <textbook bookID="3">

        <title>Kali Linux Revealed: Mastering the Penetration Testing Distribution</title>
        <author>Raphael Hertzog</author>

        <ISBN>0997615605</ISBN>
        <publisher>Offsec Press</publisher>
        <date>06/05/2017</date>
        <abstracts>In this book, we'll focus on the Kali Linux platform itself, and help you understand and maximize Kali from the ground up.</abstracts>
        <category>IT</category>
        <reservation>no</reservation>
        <condition>good</condition>
        <lister>Michael Nguyen</lister>

    </textbook>
    <textbook bookID="4">

        <title>Fundamentals of economics</title>
        <author>William Boyes</author>

        <ISBN>0538481196</ISBN>
        <publisher>Cengage Learning</publisher>
        <date>2011</date>
        <abstracts>Based on the comprehensive two-semester text by the same authors, this version of Economics boils down the formal economic theories and concepts into their essential parts, emphasizing  domestic and international applications and policy issues. </abstracts>
        <category>Business</category>
        <reservation>yes</reservation>
        <condition>poor</condition>
        <lister>Joel Miller</lister>

    </textbook>
    
    <textbook bookID="5">
        <title>Social Issues in Diagnosis</title>
        <author>Annemarie Goldstein Jutel, Kevin Dew</author>

        <ISBN>9781421413006</ISBN>
        <publisher>John Hopkins University Press</publisher>
        <date>2014</date>
        <abstracts>Diagnosis, the classification tool of medicine, serves an important social role. It confers social status on those who diagnose, and it impacts the social status of those diagnosed. Studying diagnosis from a sociological perspective offers clinicians and students a rich and sometimes provocative view of medicine and the cultures in which it is practiced. Social Issues in Diagnosis describes how diagnostic labels and the process of diagnosis are anchored in groups and structures as much as they are in the interactions between patient and doctor.</abstracts>
        <category>Medical</category>
        <reservation>no</reservation>
        <condition>new</condition>
        <lister>Tweeny Scott</lister>

    </textbook>
    
    <textbook bookID="6">
        <title>Violent Python</title>
        <author>TJ O'connor</author>

        <ISBN> 1597499579</ISBN>
        <publisher>Syngress</publisher>
        <date>9/22/2012</date>
        <abstracts>Violent Python shows you how to move from a theoretical understanding of offensive computing concepts to a practical implementation. </abstracts>
        <category>IT</category>
        <reservation>no</reservation>
        <condition>new</condition>
        <lister>Troy Baker</lister>

    </textbook>
</textbooks>
